export const siteConfig = {
  name: 'Dua Insan Organizer',
  tagline: 'Pendamping Setia Menuju Hari Bahagia',
  description:
    'Layanan Wedding Organizer & Wedding Planner profesional di Pekanbaru, Riau dan sekitarnya. Mewujudkan prosesi pernikahan yang khidmat, teratur, dan berkesan.',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  logo: '/images/logo/logo.png',
  contact: {
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '08216098313',
    phone: '0821-6098-313',
    email: 'organizerduainsan@gmail.com',
    instagram: '@duainsanorganizer',
    instagramUrl: 'https://instagram.com/duainsanorganizer',
    tiktok: '@duainsanorganizer',
    address: 'Pekanbaru, Riau (Temu Janji di Cafe & Kunjungan ke Kediaman)',
    city: 'Pekanbaru',
    hours: 'Senin - Minggu: 09.00 - 21.00 WIB (Dengan Janji Temu Fleksibel)',
  },
  navLinks: [
    { label: 'Beranda', href: '/' },
    { label: 'Tentang Kami', href: '/tentang' },
    { label: 'Layanan', href: '/layanan' },
    { label: 'Paket Wedding', href: '/paket' },
    { label: 'Portofolio', href: '/portfolio' },
    { label: 'Testimoni', href: '/testimoni' },
    { label: 'FAQ', href: '/faq' },
    { label: 'Kontak', href: '/kontak' },
  ],
  adminNavLinks: [
    { label: 'Overview', href: '/admin' },
    { label: 'Leads / Inquiry', href: '/admin/leads' },
    { label: 'Paket Wedding', href: '/admin/paket' },
    { label: 'Layanan', href: '/admin/layanan' },
    { label: 'Portofolio', href: '/admin/portfolio' },
    { label: 'Testimoni', href: '/admin/testimoni' },
    { label: 'FAQ', href: '/admin/faq' },
    { label: 'Pengaturan', href: '/admin/pengaturan' },
  ],
};
